### ISSUE TITLE
Figure error

### ISSUE THREAD

**Issue by baoyukun** [baoyukun/PAF-Telecom-ParisTech#1]
In the second picture which is drawn by @zhufangda , it should be "**crawler**" instead of "**cralwer**".
Hope fixing it as soon as possible, thanks :kissing_heart:

**Comment by baoyukun** [comment]
And the same problem for "**Base des données**" instead of "**Base de donné(e)**", as well as "**extraire**" instead of "**exraire**". 麻烦你了方达 @zhufangda 
Good night and bon weekend! :balloon::balloon::balloon:

**Comment by zhufangda** [comment]
This issus has fixed. Thanks. @baoyukun
