### ISSUE TITLE
Add poster to our project

### ISSUE THREAD

**Issue by baoyukun** [baoyukun/PAF-Telecom-ParisTech#4]
Where can be found the poster? @ninofiliu @zhufangda @mcdiallo 
It's cool to just put it in the final resume of README.md file. :balloon::balloon::balloon:

**Comment by ninofiliu** [comment]
okay imma add it!

**Comment by ninofiliu** [comment]
https://github.com/baoyukun/PAF-Telecom-ParisTech/blob/master/resource/poster-7.pdf here you go

**Comment by baoyukun** [comment]
OK, it's done. Very good job. Cheers. @ninofiliu
